In [4]:
import torch
import torch.nn as nn  # building blocks of nn used for activation function or creating layers

In [25]:
# input
# tenser -> is a multi-dim array
"""
0D -> scaler (const vals)
1D -> vector
2D -> matrix
3D+ -> tensors (used in images and videos store)
"""
torch.manual_seed(42)  # used for same output evrytime as random_state
inputs = torch.tensor([1.0, 2.0, 3.0])

In [26]:
# creating neuron
# Linear Activation funx -> calculate the weighted sum
neuron = nn.Linear(in_features=3, out_features=1)

In [27]:
# output
output = neuron(inputs)

In [28]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [29]:
# verify  ... formula
neuron.weight @ inputs + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)

In [30]:
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)

In [31]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)