In [1]:
import numpy as np
import time

In [2]:
# Time
size = 10_000000

py_list = list(range(size))
start = time.time()
sq_list = [n**2 for n in py_list]
end = time.time()
print(f"Python list Squar Time: {end - start}")

np_array = np.array(py_list)
start = time.time()
sq_array = np_array ** 2
end = time.time()
print(f"Numpy Array Squar time: {end-start}")

Python list Squar Time: 1.450002908706665
Numpy Array Squar time: 0.04768967628479004


In [3]:
# memmory
import sys

print(f"Python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")

print(f"Numpy array size = {np_array.nbytes} bytes")

Python list size = 800000560000000 bytes
Numpy array size = 80000000 bytes


In [4]:
# Create numpy array- from list
# 0 dimension array
arr1 = np.array(25)
print(arr1, type(arr1), arr1.shape)

# 1 dimension array
arr2 = np.array([25])
print(arr2, type(arr2), arr2.shape)

arr3 = np.array([1, 2, 3, 4, 5])
print(arr3, type(arr3), arr3.shape)

arr4 = np.array([1, 2, 3, 4, 5, "Prime"])
print(arr4, type(arr4), arr4.shape)

# 2 dimension array
arr2D = np.array([[1, 2, 3], [4, 5, 5], [7, 8, 9], [10, 11, 12]])
print(arr2D, type(arr2D), arr2D.shape, arr2D.ndim)

25 <class 'numpy.ndarray'> ()
[25] <class 'numpy.ndarray'> (1,)
[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'Prime'] <class 'numpy.ndarray'> (6,)
[[ 1  2  3]
 [ 4  5  5]
 [ 7  8  9]
 [10 11 12]] <class 'numpy.ndarray'> (4, 3) 2


In [5]:
# other ways to create numpy array from scratch

arr1 = np.zeros([2, 3], dtype="i4")
print(arr1, arr1.shape)

arr2 = np.ones([2, 3, 2], dtype="i4")
print(arr2, arr2.shape, arr2.ndim)

arr3 = np.full([2, 3], "Ranjan")
print(arr3, arr3.shape)

arr4 = np.arange(5, 50, 5)
print(arr4, arr4.shape)

arr5 = np.linspace(1, 100, 5, True) 
print(arr5, arr5.shape)

arr6 = np.eye(4)
arr6 = np.identity(3)
print(arr6, arr6.shape)



[[0 0 0]
 [0 0 0]] (2, 3)
[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]] (2, 3, 2) 3
[['Ranjan' 'Ranjan' 'Ranjan']
 ['Ranjan' 'Ranjan' 'Ranjan']] (2, 3)
[ 5 10 15 20 25 30 35 40 45] (9,)
[  1.    25.75  50.5   75.25 100.  ] (5,)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)


In [6]:
# Properties
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

# type casting / change
float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
2
int64
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [7]:
# Operation on Arrays

arr = np.array([[1,2,3], [4 ,5 ,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3, 2))
print(reshaped, reshaped.shape)

flattened = arr.flatten()  # create new copy: owns data
print(flattened, flattened.shape, flattened.base)

raveled = arr.ravel()  # not create new copy create view : refer to original data
print(raveled, raveled.shape, raveled.base)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,) None
[1 2 3 4 5 6] (6,) [[1 2 3]
 [4 5 6]]


In [8]:
# Indexing
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Normal Indexing
print(arr[0][2])
print(arr[0,2])

3
3


In [9]:
# Fancy Indexing
arr = np.array([1, 2, 3, 4, 5])

idx = [0, 1, 3]
print(arr[idx])

[1 2 4]


In [10]:
# Boolean Indexing => true or false
arr = np.array([1, 2, 3, 4, 5])

print(arr[arr%2 == 0])
print(arr[arr%2 != 0])
print(arr[arr > 2])

[2 4]
[1 3 5]
[3 4 5]


In [11]:
# Slicing  -> create view
arr = np.array([1, 2, 3, 4, 5])

print(arr[:])
print(arr[2:4])
print(arr[0:5: 2])

[1 2 3 4 5]
[3 4]
[1 3 5]


In [12]:
# copy vs view

arr1 = np.array([1, 2, 3, 4, 5])
sub_arr1 = arr1[1:3]  # return view
print(sub_arr1)
sub_arr1[0] = 222
print(sub_arr1)
print(f"arr: {arr1}")

# numpy slicing return view : memory efficient, fast
# python slicing return copy: safe, slow

[2 3]
[222   3]
arr: [  1 222   3   4   5]


In [13]:
# data type

In [14]:
# Multi-Dimensional arrays

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [15]:
# 3D Array
arr3D = np.array([ [[1,2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]] ])
print(arr3D, arr3D.shape)

# indexing
print(arr3D[1,1,1])
print(arr3D[0,2,0])

# slicing
print(arr3D[:, :, 0])

arr3D[:, :, 0] = 90
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
10
5
[[ 1  3  5]
 [ 7  9 11]]
[[[90  2]
  [90  4]
  [90  6]]

 [[90  8]
  [90 10]
  [90 12]]]


In [16]:
# Brodcasting

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

print(arr1+ arr2)
print(arr1 + 5)

[ 7  9 11 13 15]
[ 6  7  8  9 10]


In [17]:
# Mathemetical Function

arr = np.array([1, 2, 3, 4, 5])

# Aggregate Function-> return single value
print(np.sum(arr))
print(np.max(arr))
print(np.argmax(arr))
print(np.min(arr))
print(np.argmin(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.var(arr))
print(np.std(arr))

15
5
4
1
0
3.0
3.0
2.0
1.4142135623730951


In [18]:
# Power function
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 4))


[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1  16  81 256 625]


In [19]:
# log & exponential

print(np.log(arr))  # base e
print(np.log10(arr))  # base 10
print(np.log2(arr))  # base 2

print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [20]:
# rounding

print(np.round(3.14))
print(np.round(3.94))  # nearest val

print(np.ceil(3.1543))
print(np.floor(3.1543))

print(np.trunc(3.48736))  # truncate(cut) all number after decimal

3.0
4.0
4.0
3.0
3.0


In [21]:

arr = np.array([1, 2, 3, 4, 2, 3, 5, 1])
print(np.unique(arr))
print(np.sort(arr))

arr = np.array([1, 2, -3, 4, -5])
print(np.abs(arr))

[1 2 3 4 5]
[1 1 2 2 3 3 4 5]
[1 2 3 4 5]
